/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/transformations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: operations["list_all_api_v1_datasets__dataset_id__transformations_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_datasets__dataset_id__transformations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diff */
        get: operations["diff_api_v1_datasets__dataset_id__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: operations["list_all_api_v1_datasets_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_v1_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Versions */
        get: operations["versions_api_v1_datasets__dataset_id__versions_get"];
        put?: never;
        /** Upload Version */
        post: operations["upload_version_api_v1_datasets__dataset_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/versions/{version_no}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version Detail */
        get: operations["version_detail_api_v1_datasets__dataset_id__versions__version_no__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/versions/{version_no}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview */
        get: operations["preview_api_v1_datasets__dataset_id__versions__version_no__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/passport": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entries */
        get: operations["entries_api_v1_datasets__dataset_id__passport_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/passport/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify */
        post: operations["verify_api_v1_datasets__dataset_id__passport_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/passport/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_api_v1_datasets__dataset_id__passport_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_version_api_v1_datasets__dataset_id__versions_post */
        Body_upload_version_api_v1_datasets__dataset_id__versions_post: {
            /** File */
            file: string;
        };
        /** DatasetCreate */
        DatasetCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Source */
            source?: string | null;
            /** License */
            license?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /**
             * Primary Key
             * @default []
             */
            primary_key: string[];
        };
        /** DatasetOut */
        DatasetOut: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Source */
            source?: string | null;
            /** License */
            license?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /**
             * Primary Key
             * @default []
             */
            primary_key: string[];
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            latest_version?: components["schemas"]["LatestVersion"] | null;
        };
        /** DiffOut */
        DiffOut: {
            /** From Version */
            from_version: number;
            /** To Version */
            to_version: number;
            /** Mode */
            mode: string;
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Schema Diff */
            schema_diff: {
                [key: string]: unknown;
            };
            /** Rows */
            rows: {
                [key: string]: {
                    [key: string]: unknown;
                }[];
            };
            /** Column Changes */
            column_changes: {
                [key: string]: number;
            };
            /** Warnings */
            warnings: string[];
            /** Page */
            page: {
                [key: string]: number;
            };
        };
        /** FileMismatch */
        FileMismatch: {
            /** Version No */
            version_no: number;
            /** Expected */
            expected: string;
            /** Actual */
            actual: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LatestVersion */
        LatestVersion: {
            /** Version No */
            version_no: number;
            /** Row Count */
            row_count: number;
            /** Column Count */
            column_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PassportEntryOut */
        PassportEntryOut: {
            /** Id */
            id: number;
            /** Dataset Id */
            dataset_id: number;
            /** Seq */
            seq: number;
            /** Entry Type */
            entry_type: string;
            /** Version Id */
            version_id: number | null;
            /** Transformation Id */
            transformation_id: number | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Actor Type */
            actor_type: string;
            /** Actor Label */
            actor_label: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Prev Hash */
            prev_hash: string;
            /** Entry Hash */
            entry_hash: string;
        };
        /** TransformationCreate */
        TransformationCreate: {
            /** Type */
            type: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown;
            };
            /** Description */
            description?: string | null;
            /** From Version */
            from_version: number;
            /** To Version */
            to_version: number;
        };
        /** TransformationOut */
        TransformationOut: {
            /** Id */
            id: number;
            /** Dataset Id */
            dataset_id: number;
            /** Type */
            type: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Description */
            description: string | null;
            /** From Version */
            from_version: number | null;
            /** To Version */
            to_version: number | null;
            /** Actor Label */
            actor_label: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyOut */
        VerifyOut: {
            /** Valid */
            valid: boolean;
            /** Entries Checked */
            entries_checked: number;
            /** First Broken Seq */
            first_broken_seq: number | null;
            /** Reason */
            reason: string | null;
            /** File Mismatches */
            file_mismatches: components["schemas"]["FileMismatch"][];
        };
        /** VersionOut */
        VersionOut: {
            /** Id */
            id: number;
            /** Dataset Id */
            dataset_id: number;
            /** Version No */
            version_no: number;
            /** Parent Version Id */
            parent_version_id: number | null;
            /** File Name */
            file_name: string;
            /** File Size */
            file_size: number;
            /** File Sha256 */
            file_sha256: string;
            /** Row Count */
            row_count: number;
            /** Column Count */
            column_count: number;
            /** Columns Schema */
            columns_schema: {
                [key: string]: unknown;
            }[];
            /** Created By */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_all_api_v1_datasets__dataset_id__transformations_get: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransformationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_v1_datasets__dataset_id__transformations_post: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
                "x-actor"?: string;
            };
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransformationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransformationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_api_v1_datasets__dataset_id__diff_get: {
        parameters: {
            query: {
                from: number;
                to: number;
                limit?: number;
                offset?: number;
            };
            header: {
                "x-api-key": string;
            };
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_api_v1_datasets_get: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_v1_datasets_post: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
                "x-actor"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_api_v1_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    versions_api_v1_datasets__dataset_id__versions_get: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_version_api_v1_datasets__dataset_id__versions_post: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
                "x-actor"?: string;
            };
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_version_api_v1_datasets__dataset_id__versions_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_detail_api_v1_datasets__dataset_id__versions__version_no__get: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path: {
                dataset_id: number;
                version_no: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_v1_datasets__dataset_id__versions__version_no__preview_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header: {
                "x-api-key": string;
            };
            path: {
                dataset_id: number;
                version_no: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entries_api_v1_datasets__dataset_id__passport_get: {
        parameters: {
            query?: {
                type?: string | null;
            };
            header: {
                "x-api-key": string;
            };
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PassportEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_api_v1_datasets__dataset_id__passport_verify_post: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_v1_datasets__dataset_id__passport_export_get: {
        parameters: {
            query?: never;
            header: {
                "x-api-key": string;
            };
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
